theme: jekyll-theme-minimal
title: Portfolio
description: New graduate seeking to utilize earned skills and knowledge to pursue a software engineer position. Self-driven individual with the ability to operate both independently and collaboratively in fast-paced environments. Determined to meet all goals and expectations.

